services:
  stats-server:
    build: ./stat/stat-server
    image: stat-service
    container_name: stat-server
    ports:
      - "9090:9090"

  main-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    depends_on:
      - stats-server
    ports:
      - "8080:8080"
