services:
  stats-server:
    build: ./stat/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"

  ewm-service:
    build: main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
